eFashionShop/Controllers/AdminController/AdminImageController.cs
using eFashionShop.Application.Images;
using eFashionShop.Exceptions;
using eFashionShop.ViewModels.Catalog.Images;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace eFashionShop.Controllers.AdminController
{
    public class AdminImageController : AdminBaseController
    {
        private readonly IImageService _imageService;
        private readonly IConfiguration _configuration;

        public AdminImageController(IImageService imageService,
            IConfiguration configuration)
        {
            _configuration = configuration;
            _imageService = imageService;
        }

        public async Task<IActionResult> Index(int? categoryId, int pageIndex = 1, int pageSize = 20)
        {

            var request = new GetManageImagePagingRequest()
            {
                PageIndex = pageIndex,
                PageSize = pageSize,
            };
            var data = await _imageService.GetAll(request);
            return View(data);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> AddListImages([FromForm] List<IFormFile> images)
        {
            if (images.Count < 1) return RedirectToAction("Create");
            try
            {
                var res = new List<ImageCreateRedVm>();
                foreach (var file in images)
                {
                    var image = new ImageCreateRedVm()
                    {
                        Caption = "ảnh tự tạo",
                        File = file,
                        IsFeatured = false,
                    };
                    res.Add(image);
                }
                await _imageService.AddImage(res);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {

                return BadRequest(ex);
            }
        }

        [HttpGet]
        public async Task<IActionResult> DeleteImage(int id)
        {
            if (id < 0) throw new EShopException("Delete image fail!");
            var result = await _imageService.DeleteImage(id);
            if (result) return RedirectToAction("Index");
            throw new EShopException("Delete image fail!");
        }
        [HttpGet]
        public async Task<IActionResult> SetFeaturedImage(int id)
        {
            if (id < 0) throw new EShopException("Set main image fail!");
            var result = await _imageService.SetFeaturedImage(id);
            if (result) return RedirectToAction("Index");
            throw new EShopException("Set main image fail!");
        }
    }
}

eFashionShop/Views/AdminImage/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="container-fluid">
    <h1 class="mt-4">Thêm mới ảnh</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/adminimage/index">Trờ về</a></li>
        <li class="breadcrumb-item active">Thêm mới ảnh</li>
    </ol>
    <div class="card mb-12">
        <form id="checkImage" asp-action="AddListImages" asp-controller="AdminImage" enctype="multipart/form-data" method="post">
            <div class="form-group">
                <label class="control-label"></label>
                <input name="images" type="file" multiple class="form-control" />
                <span class="text-danger"></span>
            </div>
            <input id="submitbutton" type="submit" value="Upload" class="btn btn-primary" />
        </form>
    </div>
</div>

eFashionShop/Views/AdminImage/Index.cshtml
@using eFashionShop.ViewModels.Common;
@model PagedResult<eFashionShop.ViewModels.Catalog.Images.ImageVm>
@{
    ViewData["Title"] = "Danh sách ảnh";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="container-fluid">
    <h1 class="mt-4">Danh sách ảnh</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/adminproduct/index">Trang chủ</a></li>
        <li class="breadcrumb-item active">Danh sách ảnh</li>
    </ol>
    <div class="card mb-12">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <a class="btn btn-success" asp-action="Create" asp-controller="AdminImage">Tạo mới</a>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="container">
                <div class="row">

                    @foreach (var photo in Model.Items)
                    {
                        <div class="col-2 d-flex flex-column">
                            <img src="@photo.ImagePath" class="img-thumbnail p-1">
                                                        <div class="d-flex">
                                <button disabled="@(photo.IsFeatured)"
                                class="btn btn-sm btn-success flex-grow-1"
                                type="button"
                                onclick="location.href='@Url.Action("SetFeaturedImage", "AdminImage", new { id = @photo.Id})'">
                                Main
                                </button>
                                <button disabled="@(photo.IsFeatured)"
                                class="btn btn-sm btn-danger flex-grow-1"
                                type="button"
                                onclick="location.href='@Url.Action("DeleteImage", "AdminImage", new { id = @photo.Id})'">
                                <i class="fa fa-trash"></i>
                                </button>
                                </div>
                        </div>

                    }
                </div>
            </div>
            @await Component.InvokeAsync("AdminPager", Model)
        </div>
    </div>
</div>